{
  "language": "java",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "deploy": [
    {
      "provider": "pages",
      "strategy": "git",
      "skip_cleanup": true,
      "keep_history": true,
      "on": {
        "branch": [
          "main"
        ]
      },
      "token": "SHA256:4GxfkdRTzyzxQXBoDwKdr7XWFniNSnqTUTvE/ukPVQk"
    }
  ]
}
